parameters:
    env(JWT_SECRET_KEY): "!ChangeMe!"
    env(JWT_ALGORITHM): "HS256"

lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(string:default::resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(string:default::JWT_PASSPHRASE)%'
    encoder:
        signature_algorithm: '%env(JWT_ALGORITHM)%'
